# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SONYC Initial Project Part 2' do
  use_frameworks!

  target 'SONYC Initial Project Part 2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SONYC Initial Project Part 2UITests' do
    # Pods for testing
  end

end

